// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD97U567kFkn27G3COsMNmd6iiSM2-6kuQ',
    appId: '1:576336983030:web:fa6bfdb8c50ecbd6710dd7',
    messagingSenderId: '576336983030',
    projectId: 'abohassan-1bfc9',
    authDomain: 'abohassan-1bfc9.firebaseapp.com',
    storageBucket: 'abohassan-1bfc9.appspot.com',
    measurementId: 'G-GPKRD5F1JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXlJa5BAeWUggibowpwi94YU7doH7q-w',
    appId: '1:576336983030:android:ba42e4d7ee94a731710dd7',
    messagingSenderId: '576336983030',
    projectId: 'abohassan-1bfc9',
    storageBucket: 'abohassan-1bfc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCupy1g8HGEJ8kU5MrYLqTvTDkpw9p6BsI',
    appId: '1:576336983030:ios:a055c2dab295dc2d710dd7',
    messagingSenderId: '576336983030',
    projectId: 'abohassan-1bfc9',
    storageBucket: 'abohassan-1bfc9.appspot.com',
    iosClientId: '576336983030-g419gsknidqvb3qtl3h9dfa32ac23fc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}